version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - checkout
      - run: echo "This is where we build"
  test:
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - checkout
      - run: echo "This is where we test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
